#
# bermuda-proxy-esp32-c3-minimal.yaml
#
# This is for ESP32 C3 variants, like the XIAO ESP32-C3 etc.
#
# See other configs for devices like the S3 or original esp32 etc.
#
# This package is for adding to an existing ESPHome config file, where you
# have a device already configured and you just want to add bluetooth proxy
# features and tuning for the best Bermuda performance.
#

substitutions:
  baud_rate: "0"  # If you need serial debugging, override this to 115200 or similar.
  ble_interval: 320ms
  ble_window: 300ms
  proxy_active_scan: "true"  # Set to false to avoid requesting scan info for device names etc
  proxy_enable_outbound: "True"

packages:
  Bermuda.include_common: github://agittins/bermuda-proxies/packages/bermuda-proxy-include-common.yaml

esp32:
  framework:
    sdkconfig_options:
      # Also enable this on any derivative boards (S3, C3 etc) but not the original ESP32.
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y

